server {
    listen 80;
    listen [::]:80;

    server_name craft72app.ru www.craft72app.ru;
    root /home/mun/apps/craft72-max-app/current;
    index index.html;
    access_log off;

    location ^~ /assets/ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable" always;
        add_header X-Content-Type-Options "nosniff" always;
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache" always;
        add_header Permissions-Policy "camera=(), geolocation=(), microphone=()" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header X-Content-Type-Options "nosniff" always;
    }
}
